### ISSUE TITLE
Create set files for -300 and -VIP

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/Boeing-707#2]
As we have been discussing for a while now, about all variants, I think it's time we settle down and follow the documentation we have.

So we will no longer have the 320/420 variants.
We shall have a set file for the -VIP version and one for the -300 version.

The Boeing-707.xml will contain the FDM stuff and stuff shared by both models.

**Comment by valtsu41** [comment]
Done in 1924ff6334adb461615aa6d3f831ab87016f03af (does this link work?)

**Comment by valtsu41** [comment]
Nevermind I did not add a variant tag.

**Comment by valtsu41** [comment]
Fixed the errors.
